FROM node:20-bullseye-slim

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/* && npm ci

COPY . .
RUN npm run prisma:generate && npm run build

EXPOSE 8080

CMD ["npm", "run", "start"]
